---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: chat
  creationTimestamp: null
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/eformat/chat:latest'
      generation: 3
      importPolicy: {}
      referencePolicy:
        type: Source
